#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

source /home/pmclanahan/.virtualenvs/scrumbugz/bin/activate

if [ -n $newrev ]; then
    echo $newrev > static/revision.txt
fi

pip install -r requirements.txt --use-mirrors
python manage.py syncdb --migrate --noinput
python manage.py collectstatic --noinput
